### PR TITLE
Allow to specify coverdata files with a wildcard expression.

### PR DESCRIPTION
**Pull request by michalwski**
This PR addresses #20. Proposed changes allow to use a wildcard expression to define files with coverdata, example rebar.config entry:

```erlang
{coveralls_coverdata, "_build/**/cover/*.coverdata"}.
```

It works for me here: https://github.com/michalwski/MongooseIM/pull/120, more details you can find in travis logs [1] or [2]

[1]: https://travis-ci.org/michalwski/MongooseIM/jobs/393628236#L1651
[2]: https://travis-ci.org/michalwski/MongooseIM/jobs/393628229#L1397

### CODE REVIEW

**Comment by markusn** [comment]
Hi! The tests doesn't seem to pass after this pull.

**Comment by michalwski** [comment]
Right, I'll fix them

**Comment by michalwski** [comment]
@markusn I wonder what do you think would be better approach:
1. Add a `wildcard_reader` to the `#s` record. The default would be `filelib:wildcard/1` and in tests there would be a fun which would return `example.rb` file.
2. Add case around `filelib:wildcard` (https://github.com/markusn/coveralls-erl/pull/26/files#diff-380ecfc21bce2979875870b84a3e2b76R94) and use the original `Filename` in case `file:wildcard` returns empty list.

Or maybe some other idea?

**Comment by michalwski** [comment]
I took option 1, please let me know if that's ok.

Now 2 builds failed, as far as I can tell these failure has nothing to do with my changes. The vm on travis was not able to download Erlang archive. The same Erlang versions worked for the job with `REBAR3=false`. Probably restarting the job can help.

**Comment by markusn** [comment]
Thanks! I'll create a new hex release later this week when I have the time.

**Comment by markusn** [comment]
Version 1.5.0 on hex.pm

**Comment by michalwski** [comment]
Thanks @markusn!

**Pull request merged**
