### PR TITLE
Don't assume there is a test folder

### PR DESCRIPTION
**Pull request by markusn**

### CODE REVIEW

**Comment by egobrain** [comment]
What about this issue?

**Comment by markusn** [comment]
Hi! Do you have this issue? (And is it resolved if you use this branch?)

**Comment by egobrain** [comment]
@markusn Yes. Here is example:
https://travis-ci.org/egobrain/repo/builds/122743996 - build fails on master branch
https://travis-ci.org/egobrain/repo/builds/122742749 - and i'ts ok on patched branch

**Comment by markusn** [comment]
Ok, I will have a look at why the branch fail on travis and then merge it.

**Comment by puzza007** [comment]
👍

**Pull request merged**
