### PR TITLE
Use JSX for JSON and add additional API fields

### PR DESCRIPTION
**Pull request by RoadRunnr**
This is inspired by #25 and somewhat similar.

* it first replaces the hand crafted JSON with encoding by jsx
* it then make the coverall API more flexible by using a map for the API arguments
* and finally it adds the service_pull_request and parallel arguments

I tried to follow your coding style, but I could not get myself to mirror all of it.

### CODE REVIEW

**Comment by markusn** [comment]
@RoadRunnr thanks for your PR. I'll look into it shortly.

**Comment by markusn** [comment]
@RoadRunnr do you have example repo where you have used the new version?

**Comment by RoadRunnr** [comment]
> @RoadRunnr do you have example repo where you have used the new version?

yes:

- branch on erGW repo: https://github.com/travelping/ergw/tree/feature/coveralls
- coveralls report: https://coveralls.io/github/travelping/ergw?branch=feature/coveralls

**Comment by markusn** [comment]
@RoadRunnr released as v2.1.0

**Pull request merged**
